vnLab-Lodz/PubLab

src/renderer/components/App/App.scss
src/renderer/components/NavigationBar/NavigationBar.scss

Navbar is now sticked to the top and it's height matches the viewport. If navbar items don't fit, the navbar becomes independently scrollable
closes #94

Fixed navbar scrolling bug

---

src/renderer/components/App/App.tsx

As `ThemeProvider` was wrongly imported from `@emotion/react`, it has been change to import from `@mui/material`.

change ThemeProvide import to proper lib (MUI)

---

src/shared/redux/slices/settingsSlice.ts

Now `setSettings` reducer will not be called if reading JSON returned `null`.
Closes #142

Handle publab-settings.json not existing yet

---

.storybook/preview.js
src/renderer/components/App/App.tsx
src/renderer/components/AuthProgress/AuthProgress.tsx
src/renderer/components/AuthProgress/style.ts
src/renderer/components/Button/Button.stories.tsx
src/renderer/components/Button/Button.tsx
src/renderer/components/CustomRouter/CustomRouter.scss
src/renderer/components/DirectoryPicker/DirectoryPicker.tsx
src/renderer/components/RadioButton/RadioBtn.tsx
src/renderer/components/RadioButton/RadioGroup.stories.tsx
src/renderer/components/Select/Select.tsx
src/renderer/components/Switch/Switch.tsx
src/renderer/components/TextArea/TextArea.stories.tsx
src/renderer/components/TextArea/TextArea.tsx
src/renderer/components/TextField/TextField.stories.tsx
src/renderer/components/TextField/TextField.tsx
src/renderer/components/ViewContent/ViewContent.tsx
src/renderer/components/ViewContent/style.ts
src/renderer/theme.ts
src/renderer/views/AppSettings/AppSettings.tsx

A better implementation of themes. Most MUI components should have colors close to intended by default. Additionally, it is no longer necessary to specify whether a component is 'light' or 'dark' - it is controlled by `ThemeProvider` instead, so the component will match it's surroundings unless the color is overridden.
Main theme is 'light', as more components use it according to the design. By wrapping components in another `ThemeProvider` with `altTheme` passed to it you can change their color scheme. 
Storybook config was also updated to allow changing themes while previewing components.

Theme refactor

---

config/webpack.rules.js
src/renderer/theme.ts

Turned out to be a bit compounded. 
- The main cause was probably nesting the `@font-face` inside the `@global` (not sure why)
- Due to a [MUI bug](https://github.com/mui-org/material-ui/issues/24966), generating multiple `@font-face` rules required a workaround - otherwise they were just overriding each other.
- Path to the assets in the packaged app has to be slightly different. The main window's root url is one step shallower on the dev server.
closes #160

fix: :bug: make fonts load correctly

---

package.json
yarn.lock

The extensions are not being downloaded correctly due to an issue with the `electron-devtools-installer`. This PR changes the dependency to a version with a hotfix applied. (more [here](https://github.com/MarshallOfSound/electron-devtools-installer/issues/215))

Fix a bug with devtolls extension installation

---

src/renderer/components/CloseButton/CloseButton.tsx
src/renderer/components/Notification/Notification.tsx
src/renderer/components/Notification/style.ts
src/renderer/components/NotificationsOutlet/index.tsx
src/renderer/components/NotificationsOutlet/style.ts
src/renderer/components/Outlet/Outlet.tsx
src/renderer/internationalisation/locales/en/translation.json
src/renderer/internationalisation/locales/pl/translation.json
src/renderer/views/Description/Description.tsx
src/shared/redux/rootReducer.ts
src/shared/redux/slices/notificationsSlice.ts

Notifications can be created by dispatching a `sendNotification` action and removed by dispatching the `dismissNotification` action. They are stored in redux so that there is a possibility to dispatch them from the back-end as well. This constrains the content of the notification a little bit due to redux data being serializable so we can not just send a react node (_although one could use react dom to render a complex component to string with the loss of interactivity_) to be saved in state like it would be possible with context. 
The way to spawn a notification:
```js
dispatch(sendNotification({
title: "Title",
message: "message",
type: 'success',
autoDismiss: true, // if not set the default is false
delay: 2000, // if not set the default is 4000 | only applicable if autDismiss is true …
```

Notification spawning system

---

src/shared/redux/slices/loadPublicationsSlice.ts

Instead of a statically written union type, it is possible for it to be generated based on `Publication` keys and associated types.

Improve PublicationModification type

---

src/main/api/settings/readSyncLocations.ts
src/renderer/internationalisation/locales/en/translation.json
src/renderer/internationalisation/locales/pl/translation.json
src/renderer/views/AppSettings/subcomponents/RepoSyncSettings/RepoSyncSettings.tsx

- Locations will be auto saved if any new ones are added to the list. Missing locations like 'profile' will be added if detected.
- The default profile for enabling user's GitHub account as sync location has been translated.
Fixes #209

Improvements to sync locations

---

mui.d.ts
src/renderer/components/SearchField/SearchField.tsx
src/renderer/components/SearchField/style.ts
src/renderer/internationalisation/locales/en/translation.json
src/renderer/internationalisation/locales/pl/translation.json
src/renderer/theme.ts
src/renderer/views/ProjectsList/ProjectsList.tsx
src/renderer/views/ProjectsList/formatTags.ts
src/renderer/views/ProjectsList/subcomponents/ProjectSearch/ProjectSearch.tsx

The functionality was implemented, the UI is based on the search box in the Files view design. 
It is possible to search by tag or by title. Right now only the publications that match all search terms are shown, but it will be easy to change it to "match any term" or tie the behavior to a switch/checkbox if we decide it will be an improvement.  
The layout is somewhat resistant to excessive input, but more than 2-3 lines will look off. 
Closes #183

Implement project list search

---

src/main/api/git/stage.ts
src/main/api/git/status.ts
src/renderer/views/Files/Files.tsx
src/renderer/views/Files/subcomponents/FileTreeItem/FileTreeItem.tsx
src/shared/utils/paths.ts
src/shared/utils/repoStatus/tree.ts

Code was changed to use absolute, platform specific path format whenever possible. When utilizing `isomorphic-git`'s features, paths are converted back and forth using the two functions in `paths.ts`.
Closes #219

Make paths formats more uniform

---

src/renderer/components/LoginComponent/LoginComponent.tsx
src/renderer/components/LoginComponent/style.ts

- The view now fits within the viewport.
- Some additional margins have been given to elements to protect from being squashed on tiny wee viewports.

Fix login screen styles

---

src/main/api/publications/generate.ts
src/main/api/publications/updateConfig.ts
src/main/lib/gatsbyConfigHandler.ts
src/renderer/views/Settings/Settings.tsx

Now config changes are also reflected in `gatsby-config`. Additionaly, publication `package.json` is updated too.
Changed files will be immediately commited and pushed to the remote. 
e.g. closes #223

Gatsby-config modification

---

src/main/lib/publicationFinder.ts
src/renderer/components/App/App.tsx
src/shared/redux/helpers/utilSelectors.ts

Guard to not fetch remote publications when the token is missing has been put in place.
Fixes #229

Guard repo fetch if token is not present

---

.storybook/__mocks__/fs.js
.storybook/main.js
package.json
src/main/api/publications/generate.ts
src/main/lib/gatsbyProjectGenerator.ts
src/renderer/components/CollabPicker/CollabPicker.stories.tsx
src/renderer/components/Languages/LanguagesPicker.tsx
src/renderer/components/Notification/Notification.stories.tsx
src/renderer/components/PackageManagerPicker/PackageManagerPicker.tsx
src/renderer/components/RadioButton/RadioBtn.tsx
src/renderer/components/RadioButton/RadioGroup.stories.tsx
src/renderer/components/Switch/Switch.stories.tsx
src/renderer/components/Switch/Switch.tsx
src/renderer/components/TechnologiesPicker/TechnologiesPicker.tsx
src/renderer/internationalisation/locales/en/translation.json
src/renderer/internationalisation/locales/pl/translation.json
src/renderer/views/AddProject/subcomponents/Steps/Steps.tsx
src/shared/redux/slices/addPublicationWizardSlice.test.ts
src/shared/redux/slices/addPublicationWizardSlice.ts
yarn.lock

Certain creation options exclude each other. For now if publication is multilingual the project gets generated with sass. Typescript is used in all projects. I think in the future we will need to have a look if the template approach is the right one or should we modify the code on the users machine to get the publication template into a form that satisfies the condition. Not too important for now.
- Fixed some storybook issues
- Improved radio and switch disabled states
- Disabled certain switches and radios in project creation
- Added tooltips to explain the disabled elements
- Added a creation step to choose whether the publication is multilingual
- Updated [vnLab-templates](https://github.com/vnLab-Lodz/vnLab-templates/commits/main) repository in …

Project creation based on templates

---

src/renderer/components/PublicationHeader/PublicationHeader.tsx
src/renderer/internationalisation/locales/en/translation.json
src/renderer/internationalisation/locales/pl/translation.json
src/renderer/views/Files/Files.tsx
src/renderer/views/Files/subcomponents/FileExplorer/FileExplorer.tsx
src/renderer/views/Files/subcomponents/FileSearchExplorer/FileSearchExplorer.tsx
src/renderer/views/Files/subcomponents/FileTree/FileTree.tsx

Files searching has been implemented. It only searches in publication for now. In the future we could play around with rendering the folders and files sections as accordions to allow collapsing in case user wants only results of one of these. Grouping the files by path could also be given a little bit of thought in a similar fashion to commits view. 
Closes #224

Files search

---

src/main/lib/gitRepoHandler.ts
src/renderer/internationalisation/locales/en/translation.json
src/renderer/internationalisation/locales/pl/translation.json
src/renderer/views/ProjectsList/subcomponents/ProjectsTable/ProjectsTable.tsx

Couldn't immediately find any improvement for the `checkout` action in `isomorphic-git` so decided to improve the usability by not doing the `checkout` if the target branch is the current branch and added a simple loader for the publication activation in order to notify the user that things are happening in the background.
Relates to #256

Improve checkout when switching publications

---

src/renderer/views/Files/Files.tsx

‼️ This PR depends on #257. It will be a draft till that one is merged. 
✅ The code in this PR is final and can be review. I put #257 as target branch to allow for easy review of the relevant code.
Tree in the Files view is no sorted in the human readable alphabetical-numerical way instead of the "Windows" way.
Closes #241

Sort files in human readable form

---

src/renderer/utils/formatPath.tsx
src/renderer/views/Changes/subcomponents/ChangedFiles/FilesByFolder.tsx
src/renderer/views/Files/subcomponents/FileSearchExplorer/FileSearchExplorer.tsx

‼️ This PR depends on #258. It will be a draft till that one is merged. 
✅ The code in this PR is final and can be review. I put #258 as target branch to allow for easy review of the relevant code.
Fixed the commits view and made the `formatPath` function reusable for us in the files search results.
Closes #242

Reinstate commit file grouping by dir path

---

package.json
src/main/index.ts
yarn.lock

This should fix issues with `child_process.spawn` not working correctly in the packaged macOS version. 
AFAIK the root cause of the issue was `process.env.PATH` being passed weirdly to GUI apps on macOS. Fortunately, there is a package for that. 
It is important to keep the version at 3.0.0 - newer versions are written with ESM in mind, and electron does not support that out of the box. (more details [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-import-esm-in-electron))

Fix child_process.spawn issues on macOS

---

src/renderer/views/ProjectsList/subcomponents/ProjectsTable/ProjectsTable.tsx
src/renderer/views/ProjectsList/subcomponents/ProjectsTable/TableHeaders.tsx
src/renderer/views/ProjectsList/subcomponents/ProjectsTable/hooks/useActivePublication.ts
src/renderer/views/ProjectsList/subcomponents/ProjectsTable/hooks/useProcessedProjectList.ts
src/renderer/views/ProjectsList/subcomponents/ProjectsTable/hooks/useSelectedProject.ts
src/renderer/views/ProjectsList/subcomponents/ProjectsTable/style.ts
src/renderer/views/ProjectsList/types.ts

Implemented as described in #182. `ProjectsTable.tsx` was getting a bit logic-heavy, so it was refactored into separate hooks. 
Closes #182

182 project list sort filter
